-- Generated using GM2MC ( GTA:SA Models To MTA:SA Converter )

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'patriot.txd' ) 
engineImportTXD ( txd, 470 ) 
dff = engineLoadDFF('patriot.dff', 470 ) 
engineReplaceModel ( dff, 470 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'bobcat.txd' ) 
engineImportTXD ( txd, 422 ) 
dff = engineLoadDFF('bobcat.dff', 422 ) 
engineReplaceModel ( dff, 422 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'quad.txd' ) 
engineImportTXD ( txd, 471 ) 
dff = engineLoadDFF('quad.dff', 471 ) 
engineReplaceModel ( dff, 471 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'sanchez.txd' ) 
engineImportTXD ( txd, 468 ) 
dff = engineLoadDFF('sanchez.dff', 468 ) 
engineReplaceModel ( dff, 468 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'bike.txd' ) 
engineImportTXD ( txd, 509 ) 
dff = engineLoadDFF('bike.dff', 509 ) 
engineReplaceModel ( dff, 509 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'barracks.txd' ) 
engineImportTXD ( txd, 433 ) 
dff = engineLoadDFF('barracks.dff', 433 ) 
engineReplaceModel ( dff, 433 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'maverick.txd' ) 
engineImportTXD ( txd, 487 ) 
dff = engineLoadDFF('maverick.dff', 487 ) 
engineReplaceModel ( dff, 487 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'newmav.txd' ) 
engineImportTXD ( txd, 497 ) 
dff = engineLoadDFF('newmav.dff', 497 ) 
engineReplaceModel ( dff, 497 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'clover.txd' ) 
engineImportTXD ( txd, 542 ) 
dff = engineLoadDFF('clover.dff', 542 ) 
engineReplaceModel ( dff, 542 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'mesa.txd' ) 
engineImportTXD ( txd, 500 ) 
dff = engineLoadDFF('mesa.dff', 500 ) 
engineReplaceModel ( dff, 500 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'burrito.txd' ) 
engineImportTXD ( txd, 482 ) 
dff = engineLoadDFF('burrito.dff', 482 ) 
engineReplaceModel ( dff, 482 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'fbirancher.txd' ) 
engineImportTXD ( txd, 490 ) 
dff = engineLoadDFF('fbirancher.dff', 490 ) 
engineReplaceModel ( dff, 490 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'bus.txd' ) 
engineImportTXD ( txd, 431 ) 
dff = engineLoadDFF('bus.dff', 431 ) 
engineReplaceModel ( dff, 431 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'dodo.txd' ) 
engineImportTXD ( txd, 593 ) 
dff = engineLoadDFF('dodo.dff', 593 ) 
engineReplaceModel ( dff, 593 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'rancher.txd' ) 
engineImportTXD ( txd, 489 ) 
dff = engineLoadDFF('rancher.dff', 489 ) 
engineReplaceModel ( dff, 489 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'moonbean.txd' ) 
engineImportTXD ( txd, 418 ) 
dff = engineLoadDFF('moonbean.dff', 418 ) 
engineReplaceModel ( dff, 418 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'sandking.txd' ) 
engineImportTXD ( txd, 495 ) 
dff = engineLoadDFF('sandking.dff', 495 ) 
engineReplaceModel ( dff, 495 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'raindance.txd' ) 
engineImportTXD ( txd, 563 ) 
dff = engineLoadDFF('raindance.dff', 563 ) 
engineReplaceModel ( dff, 563 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'polmav.txd' ) 
engineImportTXD ( txd, 488 ) 
dff = engineLoadDFF('polmav.dff', 488 ) 
engineReplaceModel ( dff, 488 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'camper.txd' ) 
engineImportTXD ( txd, 483 ) 
dff = engineLoadDFF('camper.dff', 483 ) 
engineReplaceModel ( dff, 483 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'buffalo.txd' ) 
engineImportTXD ( txd, 402 ) 
dff = engineLoadDFF('buffalo.dff', 402 ) 
engineReplaceModel ( dff, 402 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'freeway.txd' ) 
engineImportTXD ( txd, 463 ) 
dff = engineLoadDFF('freeway.dff', 463 ) 
engineReplaceModel ( dff, 463 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'injector.txd' ) 
engineImportTXD ( txd, 424 ) 
dff = engineLoadDFF('injector.dff', 424 ) 
engineReplaceModel ( dff, 424 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'reefer.txd' ) 
engineImportTXD ( txd, 453 ) 
dff = engineLoadDFF('reefer.dff', 453 ) 
engineReplaceModel ( dff, 453 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'copcarla.txd' ) 
engineImportTXD ( txd, 596 ) 
dff = engineLoadDFF('copcarla.dff', 596 ) 
engineReplaceModel ( dff, 596 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'nevada.txd' ) 
engineImportTXD ( txd, 553 ) 
dff = engineLoadDFF('nevada.dff', 553 ) 
engineReplaceModel ( dff, 553 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'tropic.txd' ) 
engineImportTXD ( txd, 454 ) 
dff = engineLoadDFF('tropic.dff', 454 ) 
engineReplaceModel ( dff, 454 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'phoenix.txd' ) 
engineImportTXD ( txd, 603 ) 
dff = engineLoadDFF('phoenix.dff', 603 ) 
engineReplaceModel ( dff, 603 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'infi.txd' ) 
engineImportTXD ( txd, 411 ) 
dff = engineLoadDFF('infi.dff', 411) 
engineReplaceModel ( dff, 411 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'huntley.txd' ) 
engineImportTXD ( txd, 579 ) 
dff = engineLoadDFF('huntley.dff', 579 ) 
engineReplaceModel ( dff, 579 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'landstalker.txd' ) 
engineImportTXD ( txd, 400 ) 
dff = engineLoadDFF('landstalker.dff', 400) 
engineReplaceModel ( dff, 400 )
end)

addEventHandler('onClientResourceStart',getResourceRootElement(getThisResource()),function () 
txd = engineLoadTXD ( 'sparrow.txd' ) 
engineImportTXD ( txd, 469 ) 
dff = engineLoadDFF('sparrow.dff', 469 ) 
engineReplaceModel ( dff, 469 )
end)

